DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS events;

-- draft
  CREATE TABLE IF NOT EXISTS events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      --
      category_id BIGINT NOT NULL,

      CONSTRAINT pk_event PRIMARY KEY (id),
      CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id)
  );

  -- draft
  CREATE TABLE IF NOT EXISTS categories (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(150) NOT NULL
      CONSTRAINT pk_category PRIMARY KEY (id),
      CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
  );

-- draft
CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(50) NOT NULL,

    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

--CREATE INDEX idx_hit_timestamp ON hits(timestamp);
--CREATE INDEX idx_hit_uri ON hits(uri);
--CREATE INDEX idx_hit_ip ON hits(ip);